- name: ensure a list of prerequisite packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - elrepo-release
    - epel-release

- name: install Wireguard and tools
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - kmod-wireguard
    - wireguard-tools

- name: Create installation directory if it does not exist
  file:
    path: /etc/wireguard
    state: directory
    mode: '0755'

- name: Generate public key
  shell: 'wg genkey | sudo tee /etc/wireguard/privatekey | wg pubkey | sudo tee /etc/wireguard/publickey'
