- name: Create installation directory if it does not exist
  file:
    path: /etc/wireguard
    state: directory
    mode: '0755'

- name: Generate public key
  shell: 'wg genkey | sudo tee /etc/wireguard/privatekey | wg pubkey | sudo tee /etc/wireguard/publickey'
  register: server_private_key

- name: Ensure user group exists
  group:
    name: wireguard
    state: present

- name: Create user
  user:
    name: wireguard
    comment: Wireguard
    group: wireguard

- name: Template config file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: wireguard
    group: wireguard
    mode: '0644'
