- name: Install prerequisites
  apt:
    pkg:
      - apt-transport-https

- name: Download and install the Public Signing Key
  shell: 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

- name: Save repository definition
  shell: 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list'

- name: Install Metric Beat package
  apt:
    pkg:
      - metricbeat
    update_cache: yes

- name: Enable service
  systemd:
    state: started
    name: metricbeat
    enabled: yes
